# Generated by Django 4.2.20 on 2025-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Leave empty — it will be generated automatically upon saving', max_length=128, null=True),
        ),
    ]
